#ifndef W3DLANGTABLA_H
#define W3DLANGTABLA_H

// GENERADO. No editar a mano: se regenera desde el diccionario (tools/genlang.py).
//
// ORDENADA por el texto ingles en orden strcmp: T() la bisecta y ese orden es el invariante del que
// depende. El generador lo verifica antes de escribir este archivo (--check).
//
// OJO: el orden se calcula sobre el string en RUNTIME (el literal DESESCAPADO, en bytes utf-8), que es lo
// que compara strcmp -- NO sobre el literal como se lee aca. Con \" el literal empieza con la barra (0x5C)
// y en runtime con la comilla (0x22): ordenar por el texto escapado deja esas filas fuera de lugar y la
// biseccion se pierde (se ve como traducciones "faltantes" aunque esten en la tabla). Por eso las entradas
// que arrancan con comilla van ARRIBA de todo y no donde las pondria un sort del archivo.
//
// La clave es el propio ingles -> lo que no este aca sale en ingles, que es exactamente lo que se quiere.

struct W3dLangEntrada { const char* en; const char* es; const char* pt; };

static const W3dLangEntrada W3dLangTabla[] = {
    { "\" already exists. Do you want to replace it?", "\" ya existe. ¿Reemplazarlo?", "\" já existe. Deseja substituí-lo?" },
    { "\"%s\" is in use by %d user(s). Delete it anyway? Its users will be left without it.", "\"%s\" está en uso por %d usuario(s). ¿Borrarlo igual? Sus usuarios quedarán sin él.", "\"%s\" está em uso por %d usuário(s). Excluir mesmo assim? Seus usuários ficarão sem ele." },
    { "\"%s\" is used by %d object(s). Delete it anyway?", "\"%s\" lo usan %d objeto(s). ¿Borrarlo igual?", "\"%s\" é usado por %d objeto(s). Excluir mesmo assim?" },
    { "%d animation curve(s) of the selection no longer animate anything (Ctrl+Z brings them back)", "%d curva(s) de animación de la selección ya no animan nada (Ctrl+Z las devuelve)", "%d curva(s) de animação da seleção não animam mais nada (Ctrl+Z as devolve)" },
    { "%d object(s) got their own copy of the mesh", "%d objeto(s) pasaron a tener su propia copia de la malla", "%d objeto(s) passaram a ter sua própria cópia da malha" },
    { "%d object(s) of the project use 3D meshes of \"%s\": each one gets its own copy (Ctrl+Z undoes it). Unlink it?", "%d objeto(s) del proyecto usan mallas 3D de \"%s\": cada uno pasa a tener su propia copia (Ctrl+Z lo deshace). ¿Desvincularla?", "%d objeto(s) do projeto usam malhas 3D de \"%s\": cada um passa a ter sua própria cópia (Ctrl+Z desfaz). Desvincular?" },
    { "%d reference(s) of the unpacked objects now find another object with the same name", "%d referencia(s) de los objetos desempaquetados ahora encuentran otro objeto con el mismo nombre", "%d referência(s) dos objetos desempacotados agora encontram outro objeto com o mesmo nome" },
    { "%d resources are in use (%d users). Delete them anyway? Their users will be left without them.", "%d recursos están en uso (%d usuarios). ¿Borrarlos igual? Sus usuarios quedarán sin ellos.", "%d recursos estão em uso (%d usuários). Excluir mesmo assim? Seus usuários ficarão sem eles." },
    { "(Esc to cancel)", "(Esc para cancelar)", "(Esc para cancelar)" },
    { "(coming soon)", "(próximamente)", "(em breve)" },
    { "(default)", "(por defecto)", "(padrão)" },
    { "(empty)", "(vacío)", "(vazio)" },
    { "(no properties yet)", "(sin propiedades aún)", "(sem propriedades ainda)" },
    { "(none)", "(ninguna)", "(nenhuma)" },
    { "(not shared)", "(sin compartir)", "(não compartilhada)" },
    { "2D Armature Animation", "Animación de Armature 2D", "Animação de Armature 2D" },
    { "2D armature animation: the mesh has no 2D armature", "Animación de armature 2D: la malla no tiene armature 2D", "Animação de armature 2D: a malha não tem armature 2D" },
    { "3D Cursor", "Cursor 3D", "Cursor 3D" },
    { "3D Mesh", "Malla 3D", "Malha 3D" },
    { "3D Mesh of", "Malla 3D de", "Malha 3D de" },
    { "3D Meshes", "Mallas 3D", "Malhas 3D" },
    { "3D Viewport", "Vista 3D", "Viewport 3D" },
    { ": baked", ": horneado", ": bakeado" },
    { "A W3D proxy is read-only: it can't be unpacked", "Un proxy W3D es de solo lectura: no se puede desempaquetar", "Um proxy W3D é somente leitura: não pode ser desempacotado" },
    { "A different file already exists there", "Ya hay otro archivo ahí", "Já existe outro arquivo lá" },
    { "A flipbook uses it", "Lo usa un flipbook", "Um flipbook o usa" },
    { "A game has no keyframes: choose one of its clips in the timeline to animate", "Un juego no tiene keyframes: elige uno de sus clips en la línea de tiempo para animar", "Um jogo não tem keyframes: escolha um de seus clipes na linha do tempo para animar" },
    { "A prefab can't be converted", "Un prefab no se puede convertir", "Um prefab não pode ser convertido" },
    { "A prefab can't contain itself", "Un prefab no puede contenerse a sí mismo", "Um prefab não pode conter a si mesmo" },
    { "A prefab instance only has what its prefab generates", "Una instancia de prefab solo tiene lo que genera su prefab", "Uma instância de prefab só tem o que seu prefab gera" },
    { "A project needs at least one scene", "Un proyecto necesita al menos una escena", "Um projeto precisa de pelo menos uma cena" },
    { "Abrir normal map", "Abrir Mapa de Normales", "Abrir Mapa de Normais" },
    { "Acceleration", "Aceleración", "Aceleração" },
    { "Actions", "Acciones", "Ações" },
    { "Active", "Activo", "Ativo" },
    { "Active Camera", "Cámara Activa", "Câmera Ativa" },
    { "Active Element", "Elemento activo", "Elemento ativo" },
    { "Active camera", "Cámara activa", "Câmera ativa" },
    { "Add", "Añadir", "Adicionar" },
    { "Add Circle", "Añadir Círculo", "Adicionar Círculo" },
    { "Add Color", "Añadir color", "Adicionar cor" },
    { "Add Color Layer", "Añadir Capa de Color", "Adicionar Camada de Cor" },
    { "Add Cone", "Añadir Cono", "Adicionar Cone" },
    { "Add Cube", "Añadir Cubo", "Adicionar Cubo" },
    { "Add Cylinder", "Añadir Cilindro", "Adicionar Cilindro" },
    { "Add Library...", "Agregar librería...", "Adicionar biblioteca..." },
    { "Add Plane", "Añadir Plano", "Adicionar Plano" },
    { "Add UV Group", "Añadir Grupo UV", "Adicionar Grupo UV" },
    { "Add UV Map", "Añadir Mapa UV", "Adicionar Mapa UV" },
    { "Add UV Sphere", "Añadir Esfera UV", "Adicionar Esfera UV" },
    { "Add Vertex Group", "Añadir Grupo de Vértices", "Adicionar Grupo de Vértices" },
    { "Affect Move", "Afectar Mover", "Afetar Mover" },
    { "Affect Rotate", "Afectar Rotar", "Afetar Rotacionar" },
    { "Affect Scale", "Afectar Escalar", "Afetar Escalar" },
    { "Align", "Alinear", "Alinhar" },
    { "Aligned", "Alineada", "Alinhada" },
    { "All", "Todo", "Tudo" },
    { "All Transforms", "Todas las Transformaciones", "Todas as Transformações" },
    { "Alpha", "Alfa", "Alfa" },
    { "Alpha Preview", "Vista Alpha", "Prévia Alpha" },
    { "Alpha Test", "Recorte alfa", "Recorte alfa" },
    { "Alpha channel", "Canal alfa", "Canal alfa" },
    { "Alpha kept per second", "Alfa que queda por segundo", "Alfa mantido por segundo" },
    { "Always", "Siempre", "Sempre" },
    { "Ambient", "Ambiente", "Ambiente" },
    { "An animated material uses it", "Lo usa un material animado", "Um material animado o usa" },
    { "Anchor", "Ancla", "Âncora" },
    { "Angle", "Ángulo", "Ângulo" },
    { "Angle random", "Azar del ángulo", "Ângulo aleatório (±)" },
    { "Animation", "Animación", "Animação" },
    { "Animation rendered!", "¡Animación renderizada!", "Animação renderizada!" },
    { "Animations", "Animaciones", "Animações" },
    { "Animations of", "Animaciones de", "Animações de" },
    { "Apply", "Aplicar", "Aplicar" },
    { "Apply Modifier", "Aplicar Modificador", "Aplicar Modificador" },
    { "Apply Modifiers", "Aplicar Modificadores", "Aplicar Modificadores" },
    { "Apply Transforms", "Aplicar Transformaciones", "Aplicar Transformações" },
    { "Apply: select mesh or armature object(s)", "Aplicar: selecciona malla(s) o esqueleto(s)", "Aplicar: selecione malha(s) ou armação(ões)" },
    { "Armature", "Esqueleto", "Armação" },
    { "Armature 2D", "Esqueleto 2D", "Armação 2D" },
    { "Armature Animation", "Animación de Armature", "Animação de Armature" },
    { "Aspect", "Aspecto", "Aspecto" },
    { "Assign", "Asignar", "Atribuir" },
    { "At Center", "En el centro", "No centro" },
    { "At Cursor", "En el cursor", "No cursor" },
    { "Att Constant", "Att Constante", "Att Constante" },
    { "Att Linear", "Att Lineal", "Att Linear" },
    { "Att Quadratic", "Att Cuadrática", "Att Quadrática" },
    { "Auto (active part)", "Auto (parte activa)", "Auto (parte ativa)" },
    { "Auto Clamped", "Auto Limitada", "Auto Limitada" },
    { "Auto Fit", "Ajustar al área", "Ajustar à área" },
    { "Auto Merge", "Auto Fusionar", "Auto Mesclar" },
    { "Auto frame", "Auto encuadre", "Auto enquadre" },
    { "Automatic", "Automática", "Automática" },
    { "Axis", "Eje", "Eixo" },
    { "Axis Angle", "Ángulo de Eje", "Ângulo de Eixo" },
    { "Back", "Posterior", "Traseira" },
    { "Background", "Fondo", "Fundo" },
    { "Base Color", "Color Base", "Cor Base" },
    { "Base velocity", "Velocidad base", "Velocidade base" },
    { "Billboard", "Billboard", "Billboard" },
    { "Bits", "Bits", "Bits" },
    { "Blank", "Liso", "Liso" },
    { "Blend", "Mezcla", "Mistura" },
    { "Blue", "Azul", "Azul" },
    { "Bone", "Hueso", "Osso" },
    { "Bones", "Huesos", "Ossos" },
    { "Boolean", "Booleano", "Booleano" },
    { "Boolean Object", "Objeto del booleano", "Objeto do booleano" },
    { "Border", "Borde", "Borda" },
    { "Border Color", "Color de borde", "Cor da borda" },
    { "Border Scale", "Escala del borde", "Escala da borda" },
    { "Border X", "Borde X", "Borda X" },
    { "Border Y", "Borde Y", "Borda Y" },
    { "Bottom", "Inferior", "Inferior" },
    { "Button", "Botón", "Botão" },
    { "By Distance", "Por distancia", "Por distância" },
    { "Bytes", "Bytes", "Bytes" },
    { "CPU memory", "Memoria de CPU", "Memória de CPU" },
    { "Cache Animation", "Caché de Animación", "Cache de Animação" },
    { "Camera", "Cámara", "Câmera" },
    { "Cameras", "Cámaras", "Câmeras" },
    { "Cancel", "Cancelar", "Cancelar" },
    { "Cargar normal map", "Cargar Mapa de Normales", "Carregar Mapa de Normais" },
    { "Cargar textura (imagen)", "Cargar textura (imagen)", "Carregar textura (imagem)" },
    { "Center", "Centro", "Centro" },
    { "Center X", "Centro X", "Centro X" },
    { "Center Y", "Centro Y", "Centro Y" },
    { "Center Z", "Centro Z", "Centro Z" },
    { "Changes will be lost in:", "Se perderán los cambios en:", "As alterações serão perdidas em:" },
    { "Channels", "Canales", "Canais" },
    { "Child Of", "Hijo De", "Filho De" },
    { "Children", "Hijos", "Filhos" },
    { "Choose...", "Elegir...", "Escolher..." },
    { "Circle", "Círculo", "Círculo" },
    { "Clear Depth", "Limpiar Z", "Limpar Z" },
    { "Clear Inverse", "Limpiar Inversa", "Limpar Inversa" },
    { "Clear Keyframe", "Limpiar Keyframes", "Limpar Keyframes" },
    { "Clear Original File", "Olvidar Archivo Original", "Esquecer Arquivo Original" },
    { "Clear Parent", "Desemparentar", "Desparentear" },
    { "Clear Parent Inverse", "Limpiar Inversa del Padre", "Limpar Inversa do Pai" },
    { "Clear Screen", "Limpiar Pantalla", "Limpar Tela" },
    { "Clear Seam", "Limpiar Costura", "Limpar Costura" },
    { "Clear Sharp", "Limpiar Afilado", "Limpar Aguda" },
    { "Clear Transform", "Limpiar Transformación", "Limpar Transformação" },
    { "Clear UV Group Weights", "Limpiar Pesos del Grupo UV", "Limpar Pesos do Grupo UV" },
    { "Clear and Keep Transformation", "Limpiar y Mantener Transformación", "Limpar e Manter Transformação" },
    { "Clear depth", "Limpiar Z", "Limpar Z" },
    { "Clip default", "Por defecto del clip", "Padrão do clipe" },
    { "Clipping", "Recorte", "Recorte" },
    { "Clips", "Clips", "Clipes" },
    { "Closest", "Más Cercano", "Mais Próximo" },
    { "Collapse", "Colapsar", "Colapsar" },
    { "Collection", "Colección", "Coleção" },
    { "Color", "Color", "Cor" },
    { "Color Grid", "Grilla de Colores", "Grade de Cores" },
    { "Color Layers", "Capas de color", "Camadas de cor" },
    { "Color Mode", "Modo de Color", "Modo de Cor" },
    { "Color at death", "Color al morir", "Cor ao morrer" },
    { "Columns", "Columnas", "Colunas" },
    { "Complete", "Completo", "Completo" },
    { "Cone", "Cono", "Cone" },
    { "Connect Vertex Path", "Conectar camino de vértices", "Conectar caminho de vértices" },
    { "Connect: no path between the vertices", "Conectar: no hay camino entre los vértices", "Conectar: não há caminho entre os vértices" },
    { "Connect: select exactly 2 vertices", "Conectar: seleccioná exactamente 2 vértices", "Conectar: selecione exatamente 2 vértices" },
    { "Connect: the line leaves the surface", "Conectar: la línea se sale de la superficie", "Conectar: a linha sai da superfície" },
    { "Connect: the vertices are already connected", "Conectar: los vértices ya están conectados", "Conectar: os vértices já estão conectados" },
    { "Connect: the vertices are not visible", "Conectar: los vértices no están a la vista", "Conectar: os vértices não estão visíveis" },
    { "Connected", "Conectado", "Conectado" },
    { "Connected Only", "Solo Conectados", "Só Conectados" },
    { "Constant", "Constante", "Constante" },
    { "Constraint", "Restricción", "Restrição" },
    { "Constraints", "Restricciones", "Restrições" },
    { "Container", "Contenedor", "Contêiner" },
    { "Continue without saving", "Seguir sin guardar", "Continuar sem salvar" },
    { "Convert to Game", "Convertir en juego", "Converter em jogo" },
    { "Convert to Scene", "Convertir en escena", "Converter em cena" },
    { "Copy X", "Copiar X", "Copiar X" },
    { "Copy Y", "Copiar Y", "Copiar Y" },
    { "Copy Z", "Copiar Z", "Copiar Z" },
    { "Correct UVs", "Corregir UVs", "Corrigir UVs" },
    { "Could not write config.ini", "No se pudo escribir config.ini", "Nao foi possivel gravar config.ini" },
    { "Create", "Crear", "Criar" },
    { "Create Prefab", "Crear prefab", "Criar prefab" },
    { "Cube", "Cubo", "Cubo" },
    { "Cube Projection", "Proyección de Cubo", "Projeção de Cubo" },
    { "Current Frame", "Frame Actual", "Frame Atual" },
    { "Cursor", "Cursor", "Cursor" },
    { "Cursor to Active", "Cursor al activo", "Cursor para o ativo" },
    { "Cursor to Center", "Cursor a Centro", "Cursor para Centro" },
    { "Cursor to Grid", "Cursor a la cuadrícula", "Cursor para a grade" },
    { "Cursor to Selected", "Cursor a lo seleccionado", "Cursor para o selecionado" },
    { "Cursor to Selection", "Cursor a Selección", "Cursor para Seleção" },
    { "Cursor to World Origin", "Cursor al origen del mundo", "Cursor para a origem do mundo" },
    { "Curves", "Curvas", "Curvas" },
    { "Custom", "Personalizado", "Personalizado" },
    { "Custom Normal", "Normal Personalizada", "Normal Personalizada" },
    { "Custom: edit the curve", "Personalizado: editá la curva", "Personalizado: edite a curva" },
    { "Cut", "Cortar", "Cortar" },
    { "Cylinder", "Cilindro", "Cilindro" },
    { "Cylinder Projection", "Proyección de Cilindro", "Projeção de Cilindro" },
    { "Decimals", "Decimales", "Decimais" },
    { "Default Material", "Material por Defecto", "Material Padrão" },
    { "Delete", "Borrar", "Excluir" },
    { "Delete \"%s\" (%s) with all its objects?", "¿Borrar \"%s\" (%s) con todos sus objetos?", "Excluir \"%s\" (%s) com todos os seus objetos?" },
    { "Delete \"%s\"?", "¿Borrar \"%s\"?", "Excluir \"%s\"?" },
    { "Delete %d objects?", "¿Borrar %d objetos?", "Excluir %d objetos?" },
    { "Delete %d scenes, games or prefabs with all their objects?", "¿Borrar %d escenas, juegos o prefabs con todos sus objetos?", "Excluir %d cenas, jogos ou prefabs com todos os seus objetos?" },
    { "Delete Edge Loops: select an edge loop first", "Borrar Edge Loops: selecciona un edge loop primero", "Excluir Edge Loops: selecione um edge loop primeiro" },
    { "Delete Edge Loops: select an edge shared by two faces", "Borrar Loops de Aristas: seleccioná una arista compartida por dos caras", "Excluir Loops de Arestas: selecione uma aresta compartilhada por duas faces" },
    { "Delete Folder", "Borrar carpeta", "Excluir pasta" },
    { "Delete Keyframe", "Borrar Keyframe", "Excluir Keyframe" },
    { "Delete Normals Layer", "Borrar capa de normales", "Excluir camada de normais" },
    { "Delete Palette", "Borrar paleta", "Apagar paleta" },
    { "Delete normals layer: select an object animation in the timeline", "Borrar capa de normales: elegí una animación del objeto en el timeline", "Apagar camada de normais: escolha uma animação do objeto na timeline" },
    { "Delete selected?", "¿Borrar lo seleccionado?", "Excluir a seleção?" },
    { "Delete the orphan resource", "¿Borrar el recurso huérfano", "Excluir o recurso órfão" },
    { "Delete the orphan resources", "¿Borrar los recursos huérfanos", "Excluir os recursos órfãos" },
    { "Deleted", "Borrado", "Excluído" },
    { "Density", "Densidad", "Densidade" },
    { "Depth", "Profundidad", "Profundidade" },
    { "Depth Test", "Test de Profundidad", "Teste de Profundidade" },
    { "Deselect", "Deseleccionar", "Desselecionar" },
    { "Deselect All", "Deseleccionar todo", "Desselecionar tudo" },
    { "Detect bodies", "Detectar cuerpos", "Detectar corpos" },
    { "Dies below alpha", "Muere con alfa menor a", "Morre com alfa menor que" },
    { "Difference", "Diferencia", "Diferença" },
    { "Diffuse", "Difuso", "Difuso" },
    { "Directional", "Direccional", "Direcional" },
    { "Discard the unsaved changes of", "¿Descartar los cambios sin guardar de", "Descartar as alterações não salvas de" },
    { "Disconnect", "Desconectar", "Desconectar" },
    { "Display in Edit Mode", "Mostrar en Modo Edición", "Mostrar no Modo Edição" },
    { "Display in Viewport", "Mostrar en Viewport", "Mostrar na Viewport" },
    { "Distance", "Distancia", "Distância" },
    { "Distances", "Distancias", "Distâncias" },
    { "Drag (speed kept per second)", "Arrastre (velocidad que queda por segundo)", "Arrasto (velocidade mantida por segundo)" },
    { "Drag the points, click to add", "Arrastrá los puntos, click para agregar", "Arraste os pontos, clique para adicionar" },
    { "Drop an element of a library", "Soltá un elemento de una librería", "Solte um elemento de uma biblioteca" },
    { "Drop it on a character with an armature", "Soltalo sobre un personaje con armature", "Solte sobre um personagem com armature" },
    { "Drop it on a compatible selector", "Soltalo sobre un selector compatible", "Solte sobre um seletor compatível" },
    { "Drop it on a mesh", "Soltalo sobre una malla", "Solte sobre uma malha" },
    { "Drop the library, not a clip", "Soltá la biblioteca, no un clip", "Solte a biblioteca, não um clipe" },
    { "Duplicate", "Duplicar", "Duplicar" },
    { "Duplicate Linked", "Duplicar Vinculado", "Duplicar Vinculado" },
    { "Duplicate Objects", "Duplicar Objetos", "Duplicar Objetos" },
    { "Duplicate Resource", "Duplicar recurso", "Duplicar recurso" },
    { "Duplicated", "Duplicado", "Duplicado" },
    { "Duration", "Duración", "Duração" },
    { "Edge", "Arista", "Aresta" },
    { "Edge Center", "Centro de Arista", "Centro da Aresta" },
    { "Edge Loops", "Loops de Aristas", "Loops de Arestas" },
    { "Edges", "Aristas", "Arestas" },
    { "Edit", "Editar", "Editar" },
    { "Edit Bones", "Editar Huesos", "Editar Ossos" },
    { "Edit Mode", "Modo Edición", "Modo Edição" },
    { "Edit Prefab", "Editar prefab", "Editar prefab" },
    { "Elegir archivo", "Elegir Archivo", "Escolher Arquivo" },
    { "Element of", "Elemento de", "Elemento de" },
    { "Emission", "Emisión", "Emissão" },
    { "Empty", "Vacío", "Vazio" },
    { "Enable", "Activar", "Ativar" },
    { "Enabled", "Habilitado", "Habilitado" },
    { "End", "Fin", "Fim" },
    { "End color", "Color final", "Cor final" },
    { "End:%d", "Fin:%d", "Fim:%d" },
    { "Entry", "Entrada", "Entrada" },
    { "Equirectangular (software)", "Equirectangular (software)", "Equirretangular (software)" },
    { "Error rendering animation", "Error al renderizar la animación", "Erro ao renderizar a animação" },
    { "Error: could not save the OBJ", "Error: no se pudo guardar el OBJ", "Erro: não foi possível salvar o OBJ" },
    { "Error: could not save the render", "Error: no se pudo guardar el render", "Erro: não foi possível salvar o render" },
    { "Esto modificara el vertex group y lo simplificara a 1 hueso por vertice (skinning mas rapido). Puede haber perdida de datos.", "Esto modificará el grupo de vértices y lo simplificará a 1 hueso por vértice (skinning más rápido). Puede haber pérdida de datos.", "Isto modificará o grupo de vértices e o simplificará para 1 osso por vértice (skinning mais rápido). Pode haver perda de dados." },
    { "Expand", "Expandir", "Expandir" },
    { "Export", "Exportar", "Exportar" },
    { "Export to...", "Exportar a...", "Exportar para..." },
    { "External", "Externo", "Externo" },
    { "External (choose where)...", "Externo (elegir dónde)...", "Externo (escolher onde)..." },
    { "Extrude", "Extruir", "Extrudar" },
    { "Extrude Edges", "Extruir Aristas", "Extrudar Arestas" },
    { "Extrude Faces", "Extruir Caras", "Extrudar Faces" },
    { "Extrude Vertices", "Extruir Vértices", "Extrudar Vértices" },
    { "FBX export: not available yet", "Exportar FBX: aún no disponible", "Exportar FBX: ainda não disponível" },
    { "FPS", "FPS", "FPS" },
    { "Face", "Cara", "Face" },
    { "Face Center", "Centro de cara", "Centro da face" },
    { "Face Nearest", "Cara más cercana", "Face mais próxima" },
    { "Face Normal", "Normal de Cara", "Normal de Face" },
    { "Face Project", "Proyectar en cara", "Projetar na face" },
    { "Face the camera", "Mirar a la cámara", "Olhar para a câmera" },
    { "Faces", "Caras", "Faces" },
    { "Faces triangulated", "Caras trianguladas", "Faces trianguladas" },
    { "Factor", "Factor", "Fator" },
    { "Fade in", "Aparece en", "Aparece em" },
    { "Fade out", "Desvanecer", "Desvanecer" },
    { "Falloff", "Caída", "Queda" },
    { "Far fade from", "Lejos: entera hasta", "Longe: inteira ate" },
    { "Far fade to", "Lejos: invisible desde", "Longe: invisivel desde" },
    { "File name", "Nombre de archivo", "Nome do arquivo" },
    { "File size", "Tamaño del archivo", "Tamanho do arquivo" },
    { "Fill", "Fondo", "Fundo" },
    { "Filter", "Filtro", "Filtro" },
    { "Filtering", "Filtrado", "Filtragem" },
    { "Finish the current transform first", "Termina primero la transformación en curso", "Termine primeiro a transformação em andamento" },
    { "Fit", "Ajuste", "Ajuste" },
    { "Flip", "Voltear", "Virar" },
    { "Flip Normals", "Invertir Normales", "Inverter Normais" },
    { "Flipbook frames", "Cuadros del flipbook", "Quadros do flipbook" },
    { "Floor", "Piso", "Piso" },
    { "Fog", "Niebla", "Névoa" },
    { "Folder", "Carpeta", "Pasta" },
    { "Folders", "Carpetas", "Pastas" },
    { "Follow Active Quads", "Seguir Quads Activos", "Seguir Quads Ativos" },
    { "Follow Active Quads: no neighbouring quads", "Seguir Quads Activos: no hay quads vecinos", "Seguir Quads Ativos: não há quads vizinhos" },
    { "Follow Active Quads: select faces first", "Seguir Quads Activos: selecciona caras primero", "Seguir Quads Ativos: selecione faces primeiro" },
    { "Follow Active Quads: the active face must be a selected quad", "Seguir Quads Activos: la cara activa tiene que ser un quad seleccionado", "Seguir Quads Ativos: a face ativa precisa ser um quad selecionado" },
    { "Font", "Fuente", "Fonte" },
    { "Fonts", "Fuentes", "Fontes" },
    { "Format", "Formato", "Formato" },
    { "Frame All", "Encuadrar Todo", "Enquadrar Tudo" },
    { "Frame Selected", "Encuadrar Selección", "Enquadrar Seleção" },
    { "Frame Skip", "Salto de Frames", "Salto de Frames" },
    { "Frame rate (0 = whole life)", "Cuadros por segundo (0 = toda la vida)", "Quadros por segundo (0 = vida toda)" },
    { "Frames", "Cuadros", "Quadros" },
    { "Free", "Libre", "Livre" },
    { "Front", "Frontal", "Frontal" },
    { "Front to back", "Adelante a atras", "Frente para tras" },
    { "GL Light", "Luz GL", "Luz GL" },
    { "GPU memory", "Memoria de GPU", "Memória de GPU" },
    { "Game", "Juego", "Jogo" },
    { "Game View", "Vista de juego", "Vista de jogo" },
    { "Game cache", "Caché del juego", "Cache do jogo" },
    { "Gap", "Gap", "Gap" },
    { "Generated by", "Generado por", "Gerado por" },
    { "Geometry to Origin", "Geometría al Origen", "Geometria para Origem" },
    { "Gizmo", "Gizmo", "Gizmo" },
    { "Graphics", "Gráficos", "Gráficos" },
    { "Gravity", "Gravedad", "Gravidade" },
    { "Green", "Verde", "Verde" },
    { "Grid", "Cuadrícula", "Grade" },
    { "Growth (size per second)", "Crecimiento (tamaño por segundo)", "Crescimento (tamanho por segundo)" },
    { "Growth kept per second", "Crecimiento que queda por segundo", "Crescimento mantido por segundo" },
    { "Handle Type", "Tipo de Manija", "Tipo de Alça" },
    { "Height", "Alto", "Altura" },
    { "Hide/Show", "Ocultar/Mostrar", "Ocultar/Mostrar" },
    { "Hierarchy Clip", "Clip de jerarquía", "Clipe de hierarquia" },
    { "Hierarchy Clips", "Clips de jerarquía", "Clipes de hierarquia" },
    { "Hitbox", "Hitbox", "Hitbox" },
    { "Hue", "Matiz", "Matiz" },
    { "Icon", "Icono", "Ícone" },
    { "Ignore order", "Ignorar orden", "Ignorar ordem" },
    { "Image", "Imagen", "Imagem" },
    { "Import FBX", "Importar FBX", "Importar FBX" },
    { "Import GLB", "Importar GLB", "Importar GLB" },
    { "Import OBJ", "Importar OBJ", "Importar OBJ" },
    { "Import glTF", "Importar glTF", "Importar glTF" },
    { "Imports", "Importar", "Importar" },
    { "In the .w3d", "En el .w3d", "No .w3d" },
    { "In use", "En uso", "Em uso" },
    { "Include Active", "Incluir Activo", "Incluir Ativo" },
    { "Include Edited", "Incluir Editado", "Incluir Editado" },
    { "Include Non-Edited", "Incluir No Editado", "Incluir Não Editado" },
    { "Individual Elements", "Elementos individuales", "Elementos individuais" },
    { "Individual Origins", "Orígenes individuales", "Origens individuais" },
    { "Influence", "Influencia", "Influência" },
    { "Info", "Info", "Info" },
    { "Insert Keyframe", "Insertar Keyframe", "Inserir Keyframe" },
    { "Insert Keyframe Layer", "Insertar Keyframe de Capa", "Inserir Keyframe de Camada" },
    { "Insert Keyframe: select an object animation in the timeline", "Insertar keyframe: elegí una animación del objeto en el timeline", "Inserir keyframe: escolha uma animação do objeto na timeline" },
    { "Insert Keyframe: the mesh has no normals", "Insertar keyframe: la malla no tiene normales", "Inserir keyframe: a malha não tem normais" },
    { "Inside", "Interior", "Interior" },
    { "Inside the .w3d", "Dentro del .w3d", "Dentro do .w3d" },
    { "Interpolation", "Interpolación", "Interpolação" },
    { "Interpolation Mode", "Modo de Interpolación", "Modo de Interpolação" },
    { "Intersect", "Intersección", "Interseção" },
    { "Inverse Square", "Cuadrado inverso", "Quadrado inverso" },
    { "Invert", "Invertir", "Inverter" },
    { "Invert Selection", "Invertir selección", "Inverter seleção" },
    { "It belongs to a library (read-only): open the library to edit it", "Es de una librería (solo lectura): abrí la librería para editarlo", "Pertence a uma biblioteca (somente leitura): abra a biblioteca para editá-lo" },
    { "It belongs to a prefab instance: edit the prefab or unpack the instance", "Es de una instancia de prefab: editá el prefab o desempaquetá la instancia", "Pertence a uma instância de prefab: edite o prefab ou desempacote a instância" },
    { "It can't be converted", "No se puede convertir", "Não pode ser convertido" },
    { "It can't be deleted", "No se puede borrar", "Não pode ser excluído" },
    { "It can't be linked", "No se puede vincular", "Não pode ser vinculado" },
    { "It can't be opened", "No se puede abrir", "Não pode ser aberto" },
    { "It could not be loaded", "No se pudo cargar", "Não foi possível carregar" },
    { "It couldn't be copied into the .w3d", "No se pudo copiar adentro del .w3d", "Não foi possível copiá-lo para dentro do .w3d" },
    { "It doesn't exist anymore", "Ya no existe", "Não existe mais" },
    { "It has no proyecto.json", "No tiene proyecto.json", "Não tem proyecto.json" },
    { "It is a W3D proxy: choose its library element", "Es un proxy W3D: elegí el elemento de su librería", "É um proxy W3D: escolha o elemento da sua biblioteca" },
    { "It is already linked", "Ya está vinculado", "Já está vinculado" },
    { "It is in use", "Está en uso", "Está em uso" },
    { "It is open: switch to another scene first", "Está abierta: primero cambia a otra escena", "Está aberta: primeiro troque para outra cena" },
    { "It is read-only", "Es de solo lectura", "É somente leitura" },
    { "It is the open project", "Es el proyecto abierto", "É o projeto aberto" },
    { "It isn't a .w3d project", "No es un proyecto .w3d", "Não é um projeto .w3d" },
    { "It isn't linked", "No está vinculada", "Não está vinculada" },
    { "It isn't saved in the project yet", "Todavía no está guardado en el proyecto", "Ainda não está salvo no projeto" },
    { "Its file couldn't be read", "No se pudo leer su archivo", "Não foi possível ler seu arquivo" },
    { "Its geometry couldn't be read", "No se pudo leer su geometría", "Não foi possível ler sua geometria" },
    { "Its objects couldn't be deleted", "No se pudieron borrar sus objetos", "Não foi possível excluir seus objetos" },
    { "Its objects will be deleted too (Ctrl+Z brings them back).", "Sus objetos también se borran (Ctrl+Z los devuelve).", "Seus objetos também serão excluídos (Ctrl+Z os traz de volta)." },
    { "Its proyecto.json can't be read", "Su proyecto.json no se puede leer", "Seu proyecto.json não pode ser lido" },
    { "Join", "Unir", "Juntar" },
    { "Join: no active mesh object", "Unir: no hay malla activa", "Juntar: não há malha ativa" },
    { "Join: select 2+ mesh objects (active is the target)", "Unir: selecciona 2+ mallas (la activa es el destino)", "Juntar: selecione 2+ malhas (a ativa é o destino)" },
    { "Joined into", "Unido en", "Unido em" },
    { "Keep Offset", "Mantener Offset", "Manter Deslocamento" },
    { "Language", "Idioma", "Idioma" },
    { "Layer", "Capa", "Camada" },
    { "Layout", "Layout", "Layout" },
    { "Left", "Izquierda", "Esquerda" },
    { "Left Handle X", "Manija Izq. X", "Alça Esq. X" },
    { "Levels Viewport", "Niveles Viewport", "Níveis Viewport" },
    { "Libraries", "Librerías", "Bibliotecas" },
    { "Library", "Biblioteca", "Biblioteca" },
    { "Library linked", "Librería vinculada", "Biblioteca vinculada" },
    { "Library not readable", "No se puede leer la librería", "Biblioteca ilegível" },
    { "Library unlinked", "Librería desvinculada", "Biblioteca desvinculada" },
    { "Lifetime", "Vida", "Vida" },
    { "Light", "Luz", "Luz" },
    { "Lighting", "Iluminación", "Iluminação" },
    { "Lightmap Pack", "Empaquetar Lightmap", "Empacotar Lightmap" },
    { "Lightmap Pack: select faces first", "Empaquetar Lightmap: selecciona caras primero", "Empacotar Lightmap: selecione faces primeiro" },
    { "Lights", "Luces", "Luzes" },
    { "Line (trail)", "Línea (estela)", "Linha (rastro)" },
    { "Line width", "Grosor de línea", "Espessura da linha" },
    { "Linear", "Lineal", "Linear" },
    { "Lines", "Líneas", "Linhas" },
    { "Link", "Vincular", "Vincular" },
    { "Link .w3d...", "Vincular .w3d...", "Vincular .w3d..." },
    { "Linked", "Vinculado", "Vinculado" },
    { "Load Texture", "Cargar Textura", "Carregar Textura" },
    { "Load font", "Cargar fuente", "Carregar fonte" },
    { "Load image", "Cargar imagen", "Carregar imagem" },
    { "Loaded", "Cargada", "Carregada" },
    { "Loading mode", "Carga", "Carregamento" },
    { "Loading...", "Cargando...", "Carregando..." },
    { "Location", "Posición", "Posição" },
    { "Location Only", "Solo Localización", "Somente Localização" },
    { "Location X", "Posición X", "Posição X" },
    { "Lock Normals", "Bloquear normales", "Travar normais" },
    { "Lock Orbit", "Bloquear Órbita", "Travar Órbita" },
    { "Longest clip", "Clip más largo", "Clipe mais longo" },
    { "Loop", "Loop", "Loop" },
    { "Loop (smpl)", "Loop (smpl)", "Loop (smpl)" },
    { "Loop Cut and Slide", "Loop Cut y Deslizar", "Loop Cut e Deslizar" },
    { "Loop Cut: enter Edit Mode first", "Loop Cut: entra primero en Modo Edición", "Loop Cut: entre no Modo de Edição primeiro" },
    { "Loop Cut: move = slide, Enter to confirm, Esc = center", "Loop Cut: mover = deslizar, Enter confirma, Esc = centrar", "Loop Cut: mover = deslizar, Enter confirma, Esc = centralizar" },
    { "Loop Cut: no active edge (click an edge first)", "Loop Cut: sin arista activa (clic en una arista primero)", "Loop Cut: sem aresta ativa (clique em uma aresta primeiro)" },
    { "Loop Cut: no active face (click a face first)", "Loop Cut: sin cara activa (clic en una cara primero)", "Loop Cut: sem face ativa (clique em uma face primeiro)" },
    { "Loop Cut: scroll = number of cuts, Enter to confirm", "Loop Cut: rueda = cantidad de cortes, Enter confirma", "Loop Cut: roda = número de cortes, Enter confirma" },
    { "Loop Cut: select an edge (2 verts) or a quad (4 verts)", "Loop Cut: selecciona una arista (2 vért.) o un quad (4 vért.)", "Loop Cut: selecione uma aresta (2 vért.) ou um quad (4 vért.)" },
    { "Loop Cut: select the 4 vertices of one quad", "Loop Cut: selecciona los 4 vértices de un quad", "Loop Cut: selecione os 4 vértices de um quad" },
    { "Loop Cut: tap a yellow dot to pick the cut direction (or arrows + Enter)", "Loop Cut: toca un punto amarillo para elegir la dirección del corte (o flechas + Enter)", "Loop Cut: toque um ponto amarelo para escolher a direção do corte (ou setas + Enter)" },
    { "Loop Cut: the 2 selected vertices are not an edge", "Loop Cut: los 2 vértices seleccionados no forman una arista", "Loop Cut: os 2 vértices selecionados não formam uma aresta" },
    { "Loop Cut: the active face has no edges", "Loop Cut: la cara activa no tiene aristas", "Loop Cut: a face ativa não tem arestas" },
    { "Loop Cut: the active face is not a quad", "Loop Cut: la cara activa no es un quad", "Loop Cut: a face ativa não é um quad" },
    { "Loop Select", "Seleccionar Loop", "Selecionar Loop" },
    { "Loop Select (Edge Loop)", "Seleccionar Loop (Edge Loop)", "Selecionar Loop (Edge Loop)" },
    { "Loop Select (Edge Ring)", "Seleccionar Loop (Edge Ring)", "Selecionar Loop (Edge Ring)" },
    { "Loop Select: arrows = direction, Enter to confirm", "Loop Select: flechas = dirección, Enter para confirmar", "Loop Select: setas = direção, Enter para confirmar" },
    { "Loop Select: click an", "Loop Select: clic en una", "Loop Select: clique em uma" },
    { "Make External...", "Hacer Externa...", "Tornar Externa..." },
    { "Make Internal", "Hacer Interna", "Tornar Interna" },
    { "Make Single User", "Hacer única", "Tornar única" },
    { "Margin", "Margen", "Margem" },
    { "Mark Seam", "Marcar Costura", "Marcar Costura" },
    { "Mark Sharp", "Marcar Afilado", "Marcar Aguda" },
    { "Match render", "Igual que el render", "Igual ao render" },
    { "Material", "Material", "Material" },
    { "Material Preview", "Vista Material", "Prévia Material" },
    { "Material of", "Material de", "Material de" },
    { "Materials", "Materiales", "Materiais" },
    { "Maximize", "Maximizar", "Maximizar" },
    { "Median", "Mediana", "Mediana" },
    { "Median Point", "Punto medio", "Ponto médio" },
    { "Memory", "Memoria", "Memória" },
    { "Merge", "Fusionar", "Mesclar" },
    { "Merge Distance", "Distancia de Fusión", "Distância de Mesclagem" },
    { "Mesh", "Malla", "Malha" },
    { "Mesh Parts", "Partes de Malla", "Partes de Malha" },
    { "Mesh made single user", "La malla ahora es única", "A malha agora é única" },
    { "Meshes as text", "Mallas en texto", "Malhas em texto" },
    { "Metallic", "Metálico", "Metálico" },
    { "Minimize", "Minimizar", "Minimizar" },
    { "Mipmaps", "Mipmaps", "Mipmaps" },
    { "Mirror", "Espejo", "Espelho" },
    { "Mirror Object", "Objeto Espejo", "Objeto Espelho" },
    { "Mirror X", "Espejo X", "Espelho X" },
    { "Mirror Y", "Espejo Y", "Espelho Y" },
    { "Mirror Z", "Espejo Z", "Espelho Z" },
    { "Mix", "Mix", "Mix" },
    { "Mix end", "Fin del mix", "Fim do mix" },
    { "Mix start", "Inicio del mix", "Início do mix" },
    { "Mode", "Modo", "Modo" },
    { "Modifier", "Modificador", "Modificador" },
    { "Modifier applied", "Modificador aplicado", "Modificador aplicado" },
    { "Modifiers", "Modificadores", "Modificadores" },
    { "Motion Trail", "Rastro de Movimiento", "Rastro de Movimento" },
    { "Move", "Mover", "Mover" },
    { "Move Down", "Bajar", "Descer" },
    { "Move Up", "Subir", "Subir" },
    { "Move to", "Mover a", "Mover para" },
    { "Move to Folder", "Mover a carpeta", "Mover para pasta" },
    { "Move: %d frames", "Mover: %d frames", "Mover: %d frames" },
    { "Move: %d frames, %.3f value%s", "Mover: %d frames, %.3f valor%s", "Mover: %d frames, %.3f valor%s" },
    { "Name", "Nombre", "Nome" },
    { "Near fade from", "Cerca: invisible hasta", "Perto: invisivel ate" },
    { "Near fade to", "Cerca: entera desde", "Perto: inteira desde" },
    { "New", "Nuevo", "Novo" },
    { "New Animation", "Nueva Animación", "Nova Animação" },
    { "New Color Layer", "Nueva capa de color", "Nova camada de cor" },
    { "New Copy", "Nueva copia", "Nova cópia" },
    { "New Edge/Face from Vertices", "Nueva Arista/Cara desde Vértices", "Nova Aresta/Face dos Vértices" },
    { "New Folder", "Carpeta nueva", "Nova pasta" },
    { "New Game", "Nuevo juego", "Novo jogo" },
    { "New Library", "Biblioteca nueva", "Nova biblioteca" },
    { "New Material", "Nuevo Material", "Novo Material" },
    { "New Mesh Part", "Nueva Parte", "Nova Parte" },
    { "New Palette", "Nueva paleta", "Nova paleta" },
    { "New Prefab", "Nuevo prefab", "Novo prefab" },
    { "New Scene", "Nueva escena", "Nova cena" },
    { "New Texture", "Nueva Textura", "Nova Textura" },
    { "New Texture...", "Nueva Textura...", "Nova Textura..." },
    { "New Texture: could not load", "Nueva Textura: no se pudo cargar", "Nova Textura: não foi possível carregar" },
    { "New Texture: could not save", "Nueva Textura: no se pudo guardar", "Nova Textura: não foi possível salvar" },
    { "New Texture: invalid size", "Nueva Textura: tamaño inválido", "Nova Textura: tamanho inválido" },
    { "New W3D proxy of this element", "Proxy W3D nuevo de este elemento", "Novo proxy W3D deste elemento" },
    { "New instance of this prefab", "Nueva instancia de este prefab", "Nova instância deste prefab" },
    { "New object with this 3D mesh", "Objeto nuevo con esta malla 3D", "Novo objeto com esta malha 3D" },
    { "No", "No", "Não" },
    { "No Normal Map", "Sin Mapa de Normales", "Sem Mapa de Normais" },
    { "No Texture", "Sin Textura", "Sem Textura" },
    { "No UV Group for this bone", "Este hueso no tiene UV Group", "Este osso não tem UV Group" },
    { "No active 3D viewport", "No hay vista 3D activa", "Nenhuma viewport 3D ativa" },
    { "No axes: this constraint does nothing.", "Sin ejes: esta restricción no hace nada.", "Sem eixos: esta restrição não faz nada." },
    { "No file", "Sin archivo", "Sem arquivo" },
    { "No game cache to render: play the game first (Render Image renders the current frame)", "No hay caché del juego para renderizar: primero juega (Render Image renderiza el frame actual)", "Não há cache do jogo para renderizar: jogue primeiro (Render Image renderiza o frame atual)" },
    { "No game cache: play the game to record frames. Render Image renders the current frame.", "Sin caché del juego: juega para grabar frames. Render Image renderiza el frame actual.", "Sem cache do jogo: jogue para gravar frames. Render Image renderiza o frame atual." },
    { "No library", "Sin librería", "Sem biblioteca" },
    { "No object of the scene uses it", "Ningún objeto de la escena lo usa", "Nenhum objeto da cena o usa" },
    { "No original file to forget", "No hay archivo original que olvidar", "Nao ha arquivo original a esquecer" },
    { "No prefabs yet", "Todavía no hay prefabs", "Ainda não há prefabs" },
    { "No source: this constraint does nothing.", "Sin fuente: esta restricción no hace nada.", "Sem fonte: esta restrição não faz nada." },
    { "None", "Ninguno", "Nenhum" },
    { "Normal Mapping", "Mapa de Normales", "Mapa de Normais" },
    { "Normal Size", "Tamaño de Normal", "Tamanho da Normal" },
    { "Normal View", "Vista Normal", "Vista Normal" },
    { "Normal map", "Normal map", "Normal map" },
    { "Normals", "Normales", "Normais" },
    { "Normals layer deleted", "Capa de normales borrada", "Camada de normais excluída" },
    { "Not assigned", "No se asignó", "Não atribuído" },
    { "Not deleted", "No se borró", "Não excluído" },
    { "Not linked", "No se vinculó", "Não vinculado" },
    { "Not moved", "No se movió", "Não movido" },
    { "Not opened", "No se abrió", "Não aberto" },
    { "Not saved in the project yet", "Todavía no se guardó en el proyecto", "Ainda não foi salvo no projeto" },
    { "Now click the second", "Ahora, segundo clic en", "Agora, segundo clique em" },
    { "Now external", "Ahora es externo", "Agora é externo" },
    { "Now inside the .w3d", "Ahora está dentro del .w3d", "Agora está dentro do .w3d" },
    { "Number of Cuts", "Número de Cortes", "Número de Cortes" },
    { "OBJ does not store the skeleton or animations: only the mesh will be exported (vertex groups, armature and clips will be lost). It will overwrite the file if it already exists. Continue?", "OBJ no guarda el esqueleto ni las animaciones: solo se exportará la malla (se perderán los grupos de vértices, el esqueleto y los clips). Sobrescribirá el archivo si ya existe. ¿Continuar?", "OBJ não armazena o esqueleto nem as animações: apenas a malha será exportada (grupos de vértices, armação e clipes serão perdidos). Vai sobrescrever o arquivo se já existir. Continuar?" },
    { "OBJ saved successfully!", "¡OBJ guardado correctamente!", "OBJ salvo com sucesso!" },
    { "Object", "Objeto", "Objeto" },
    { "Object (Keep Transform Without Inverse)", "Objeto (Mantener Transform. Sin Inversa)", "Objeto (Manter Transform. Sem Inversa)" },
    { "Object (Keep Transform)", "Objeto (Mantener Transform.)", "Objeto (Manter Transform.)" },
    { "Object (Without Inverse)", "Objeto (Sin Inversa)", "Objeto (Sem Inversa)" },
    { "Object Animation", "Animación del Objeto", "Animação do Objeto" },
    { "Object Mode", "Modo Objeto", "Modo Objeto" },
    { "Object Transforms", "Transformaciones de Objeto", "Transformações do Objeto" },
    { "Object animation: meshes only for now", "Animación de objeto: por ahora solo mallas", "Animação de objeto: por enquanto só malhas" },
    { "Objects", "Objetos", "Objetos" },
    { "Only active camera", "Solo cámara activa", "Só câmera ativa" },
    { "Only in Object Mode", "Solo en Object Mode", "Só no Object Mode" },
    { "Only its visibility and script values are saved", "Solo se guardan su visibilidad y los valores de sus scripts", "Só são salvos a visibilidade e os valores dos scripts" },
    { "Only selected vertices", "Solo vértices seleccionados", "Só vértices selecionados" },
    { "Opacity", "Opacidad", "Opacidade" },
    { "Open", "Abrir", "Abrir" },
    { "Open in IDE", "Abrir en el IDE", "Abrir no IDE" },
    { "Open without saving", "Abrir sin guardar", "Abrir sem salvar" },
    { "Operation", "Operación", "Operação" },
    { "Optimize Vertex Groups", "Optimizar Grupos de Vértices", "Otimizar Grupos de Vértices" },
    { "Orbit locked", "Órbita bloqueada", "Órbita bloqueada" },
    { "Orbit unlocked", "Órbita desbloqueada", "Órbita desbloqueada" },
    { "Orient", "Orient.", "Orient." },
    { "Origin to 3D Cursor", "Origen al Cursor 3D", "Origem para Cursor 3D" },
    { "Origin to Geometry", "Origen a Geometría", "Origem para Geometria" },
    { "Original file forgotten", "Archivo original olvidado", "Arquivo original esquecido" },
    { "Origins", "Orígenes", "Origens" },
    { "Orphan (no users)", "Huérfano (sin usuarios)", "Órfão (sem usuários)" },
    { "Orphans purged", "Huérfanos purgados", "Órfãos purgados" },
    { "Overlays", "Superposiciones", "Sobreposições" },
    { "Overrides", "Overrides", "Overrides" },
    { "Padding", "Padding", "Padding" },
    { "Paint background", "Pintar fondo", "Pintar fundo" },
    { "Palette", "Paleta", "Paleta" },
    { "Parent", "Padre", "Pai" },
    { "Particle Color", "Color y alfa", "Cor e alfa" },
    { "Particle Motion", "Movimiento", "Movimento" },
    { "Particle Rotation", "Rotación", "Rotação" },
    { "Particle Shape", "Forma y flipbook", "Forma e flipbook" },
    { "Particle Size", "Tamaño", "Tamanho" },
    { "Particles", "Partículas", "Partículas" },
    { "Parts", "Partes", "Partes" },
    { "Passes", "Pases", "Passes" },
    { "Path", "Ruta", "Caminho" },
    { "Per-Corner", "Por Esquina", "Por Canto" },
    { "Per-Vertex", "Por Vértice", "Por Vértice" },
    { "Per-Vertex uses one color per vertex: the colors of the other face corners are lost when painting. Continue?", "Per-Vertex usa un color por vértice: los colores de los otros face corners se pierden al pintar. ¿Continuar?", "Per-Vertex usa uma cor por vértice: as cores dos outros face corners se perdem ao pintar. Continuar?" },
    { "Perspective/Ortho", "Perspectiva/Orto", "Perspectiva/Orto" },
    { "Pick Shortest Path", "Camino Más Corto", "Caminho Mais Curto" },
    { "Pick Shortest Path: click the first", "Camino más corto: clic inicial en", "Caminho mais curto: clique inicial em" },
    { "Pixels", "Píxeles", "Pixels" },
    { "Plane", "Plano", "Plano" },
    { "Play", "Escuchar", "Ouvir" },
    { "Play once (dies at the end)", "Una sola vez (muere al terminar)", "Uma vez só (morre no fim)" },
    { "Pose Mode", "Modo Pose", "Modo Pose" },
    { "Prefab", "Prefab", "Prefab" },
    { "Prefab \"%s\": %d object(s) are outside its root object and its instances don't show them", "Prefab \"%s\": %d objeto(s) quedaron fuera de su objeto raíz y sus instancias no los muestran", "Prefab \"%s\": %d objeto(s) ficaram fora do seu objeto raiz e suas instâncias não os mostram" },
    { "Prefab Instance", "Instancia de prefab", "Instância de prefab" },
    { "Prefab created", "Prefab creado", "Prefab criado" },
    { "Prefab instances come with the prefabs phase", "Las instancias de prefab llegan con la fase de prefabs", "As instâncias de prefab chegam com a fase de prefabs" },
    { "Prefab of", "Prefab de", "Prefab de" },
    { "Prefabs", "Prefabs", "Prefabs" },
    { "Project", "Proyecto", "Projeto" },
    { "Project from View", "Proyectar desde Vista", "Projetar da Vista" },
    { "Project from View (Bounds)", "Proyectar desde Vista (Límites)", "Projetar da Vista (Limites)" },
    { "Project from View: select faces first", "Proyectar desde Vista: selecciona caras primero", "Projetar da Vista: selecione faces primeiro" },
    { "Properties", "Propiedades", "Propriedades" },
    { "Proportional Editing", "Edición Proporcional", "Edição Proporcional" },
    { "Proportional Editing: off", "Edición Proporcional: desactivada", "Edição Proporcional: desligada" },
    { "Proportional Editing: on", "Edición Proporcional: activada", "Edição Proporcional: ligada" },
    { "Proportional Size", "Tamaño Proporcional", "Tamanho Proporcional" },
    { "Proxy W3D", "Proxy W3D", "Proxy W3D" },
    { "Purge Orphans", "Purgar huérfanos", "Purgar órfãos" },
    { "Purge orphans", "¿Purgar los huérfanos", "Purgar os órfãos" },
    { "Quaternion (WXYZ)", "Cuaternión (WXYZ)", "Quaternion (WXYZ)" },
    { "Quit without saving", "Salir sin guardar", "Sair sem salvar" },
    { "Radius", "Radio", "Raio" },
    { "Radius 1", "Radio 1", "Raio 1" },
    { "Radius 2", "Radio 2", "Raio 2" },
    { "Random", "Aleatorio", "Aleatório" },
    { "Random angle (0-360)", "Ángulo al azar (0-360)", "Ângulo aleatório (0-360)" },
    { "Random spin direction", "Sentido de giro al azar", "Sentido de giro aleatório" },
    { "Random velocity", "Velocidad al azar", "Velocidade aleatória" },
    { "Rate", "Cantidad", "Quantidade" },
    { "Ray Tracing", "Trazado de rayos", "Ray Tracing" },
    { "Rays", "Rayos", "Raios" },
    { "Recalculate Normals", "Recalcular Normales", "Recalcular Normais" },
    { "Rectangle", "Rectángulo", "Retângulo" },
    { "Red", "Rojo", "Vermelho" },
    { "Reference", "Referencia", "Referência" },
    { "Reflection", "Reflejo", "Reflexo" },
    { "Relationship Lines", "Líneas de Relación", "Linhas de Relação" },
    { "Remove", "Quitar", "Remover" },
    { "Rename", "Renombrar", "Renomear" },
    { "Rename 3D Mesh", "Renombrar malla 3D", "Renomear malha 3D" },
    { "Rename Material", "Renombrar Material", "Renomear Material" },
    { "Render Animation", "Renderizar Animación", "Renderizar Animação" },
    { "Render FPS", "FPS del render", "FPS do render" },
    { "Render Image", "Renderizar Imagen", "Renderizar Imagem" },
    { "Render Preview", "Vista Render", "Prévia Render" },
    { "Render end", "Fin del render", "Fim do render" },
    { "Render saved!", "¡Render guardado!", "Render salvo!" },
    { "Render start", "Inicio del render", "Início do render" },
    { "Render to...", "Renderizar en...", "Renderizar em..." },
    { "Rendering animation...", "Renderizando animación...", "Renderizando animação..." },
    { "Rendering...", "Renderizando...", "Renderizando..." },
    { "Repeat", "Repetir", "Repetir" },
    { "Repeat Texture", "Repetir Textura", "Repetir Textura" },
    { "Reset", "Restablecer", "Redefinir" },
    { "Reset Overrides", "Quitar overrides", "Remover overrides" },
    { "Reset: select faces first", "Restablecer: selecciona caras primero", "Redefinir: selecione faces primeiro" },
    { "Resolution", "Resolución", "Resolução" },
    { "Resource", "Recurso", "Recurso" },
    { "Restart Whisk3D for this change to take effect", "Debes reiniciar Whisk3D para que este valor surta efecto", "Reinicie o Whisk3D para que esta alteracao tenha efeito" },
    { "Retarget", "Retarget", "Retarget" },
    { "Right", "Derecha", "Direita" },
    { "Right Handle X", "Manija Der. X", "Alça Dir. X" },
    { "Rings", "Anillos", "Anéis" },
    { "Rip", "Rasgar", "Rasgar" },
    { "Rip: mesh separated", "Rip: malla separada", "Rip: malha separada" },
    { "Rip: the selection does not separate the mesh", "Rip: la selección no separa la malla", "Rip: a seleção não separa a malha" },
    { "Root", "Raíz", "Raiz" },
    { "Rotate", "Rotar", "Rotacionar" },
    { "Rotate: %.1f deg  (pivot %s)", "Rotar: %.1f grados  (pivote %s)", "Rotacionar: %.1f graus  (pivô %s)" },
    { "Rotation", "Rotación", "Rotação" },
    { "Rotation Only", "Solo Rotación", "Somente Rotação" },
    { "Rotation W", "Rotación W", "Rotação W" },
    { "Rotation X", "Rotación X", "Rotação X" },
    { "Rotations only", "Solo rotaciones", "Só rotações" },
    { "Roughness", "Rugosidad", "Rugosidade" },
    { "Rows", "Filas", "Linhas" },
    { "Sample rate", "Frecuencia de muestreo", "Taxa de amostragem" },
    { "Samples", "Muestras", "Amostras" },
    { "Saturation", "Saturación", "Saturação" },
    { "Save", "Guardar", "Salvar" },
    { "Save Changes", "Guardar cambios", "Salvar alteracoes" },
    { "Save Texture", "Guardar Textura", "Salvar Textura" },
    { "Save Texture: could not encode", "Guardar Textura: no se pudo codificar", "Salvar Textura: não foi possível codificar" },
    { "Save Texture: could not write", "Guardar Textura: no se pudo escribir", "Salvar Textura: não foi possível escrever" },
    { "Save Texture: no texture", "Guardar Textura: no hay textura", "Salvar Textura: sem textura" },
    { "Save and continue", "Guardar y seguir", "Salvar e continuar" },
    { "Save and open", "Guardar y abrir", "Salvar e abrir" },
    { "Save and quit", "Guardar y salir", "Salvar e sair" },
    { "Save the project first", "Guardá el proyecto primero", "Salve o projeto primeiro" },
    { "Scale", "Escalar", "Escalar" },
    { "Scale Only", "Solo Escala", "Somente Escala" },
    { "Scale X", "Escala X", "Escala X" },
    { "Scale Y", "Escala Y", "Escala Y" },
    { "Scale Z", "Escala Z", "Escala Z" },
    { "Scale: %.2fx  (pivot %s)%s", "Escalar: %.2fx  (pivote %s)%s", "Escalar: %.2fx  (pivô %s)%s" },
    { "Scene", "Escena", "Cena" },
    { "Scene Animation", "Animación de Escena", "Animação de Cena" },
    { "Scenes", "Escenas", "Cenas" },
    { "Screen Rect", "Recorte", "Recorte" },
    { "Script", "Script", "Script" },
    { "Scripts", "Scripts", "Scripts" },
    { "Scripts that name the file", "Scripts que nombran el archivo", "Scripts que citam o arquivo" },
    { "Scripts that name the texture", "Scripts que nombran la textura", "Scripts que nomeiam a textura" },
    { "Segments", "Segmentos", "Segmentos" },
    { "Select", "Seleccionar", "Selecionar" },
    { "Select All", "Seleccionar todo", "Selecionar tudo" },
    { "Select Folder", "Elegir Carpeta", "Escolher Pasta" },
    { "Select Instance", "Elegir la instancia", "Selecionar a instância" },
    { "Select Linked", "Seleccionar Vinculado", "Selecionar Vinculado" },
    { "Select Linked: click the", "Seleccionar Vinculado: clic sobre", "Selecionar Vinculado: clique sobre" },
    { "Select Linked: select a UV first (or press L over the island)", "Seleccionar Vinculado: selecciona un UV primero (o L sobre la isla)", "Selecionar Vinculado: selecione um UV primeiro (ou L sobre a ilha)" },
    { "Select Linked: select a bone first", "Seleccionar Vinculado: selecciona un hueso primero", "Selecionar Vinculado: selecione um osso primeiro" },
    { "Select Mode", "Modo Selección", "Modo Seleção" },
    { "Select Users", "Seleccionar usuarios", "Selecionar usuários" },
    { "Select a prefab instance", "Elegí una instancia de prefab", "Selecione uma instância de prefab" },
    { "Select an object first", "Primero elige un objeto", "Primeiro escolha um objeto" },
    { "Select faces with more than 3 sides to triangulate", "Selecciona caras de más de 3 lados para triangular", "Selecione faces com mais de 3 lados para triangular" },
    { "Select the objects of the prefab", "Elegí los objetos del prefab", "Selecione os objetos do prefab" },
    { "Selected only", "Solo seleccionados", "Apenas selecionados" },
    { "Selection to Active", "Selección al activo", "Seleção para o ativo" },
    { "Selection to Cursor", "Selección a Cursor", "Seleção para Cursor" },
    { "Selection to Cursor (Keep Offset)", "Selección al cursor (mantener desfase)", "Seleção para o cursor (manter deslocamento)" },
    { "Selection to Grid", "Selección a la cuadrícula", "Seleção para a grade" },
    { "Set Active Camera: the active object is not a camera", "Cámara activa: el objeto activo no es una cámara", "Câmera ativa: o objeto ativo não é uma câmera" },
    { "Set Active Object as Camera", "Objeto Activo como Cámara", "Objeto Ativo como Câmera" },
    { "Set Inverse", "Fijar Inversa", "Definir Inversa" },
    { "Set Keyframe Handle Type", "Definir Tipo de Manija", "Definir Tipo de Alça" },
    { "Set Origin", "Definir Origen", "Definir Origem" },
    { "Set Parent", "Emparentar", "Parentear" },
    { "Set Parent To", "Emparentar a", "Parentear Para" },
    { "Set as Start Scene", "Usar como escena inicial", "Usar como cena inicial" },
    { "Settings", "Ajustes", "Ajustes" },
    { "Settings saved", "Ajustes guardados", "Ajustes salvos" },
    { "Shade Flat", "Sombrear Plano", "Sombrear Plano" },
    { "Shade Smooth", "Sombrear Suave", "Sombrear Suave" },
    { "Shape", "Forma", "Forma" },
    { "Shape keys", "Shape keys", "Shape keys" },
    { "Sharp", "Agudo", "Agudo" },
    { "Sharper", "Más agudo", "Mais agudo" },
    { "Shininess", "Dureza", "Brilho" },
    { "Shortest Path (Fill Region)", "Camino Más Corto (Rellenar Región)", "Caminho Mais Curto (Preencher Região)" },
    { "Shortest path selected", "Camino más corto seleccionado", "Caminho mais curto selecionado" },
    { "Shortest path: region filled", "Camino más corto: región rellenada", "Caminho mais curto: região preenchida" },
    { "Show Chrome UV", "Mostrar Chrome UV", "Mostrar Chrome UV" },
    { "Show Overlays", "Mostrar Superposiciones", "Mostrar Sobreposições" },
    { "Show in Edit Mode", "Ver en modo edicion", "Ver no modo de edicao" },
    { "Shrink/Fatten", "Encoger/Engrosar", "Encolher/Engrossar" },
    { "Simple", "Simple", "Simples" },
    { "Size", "Tamaño", "Tamanho" },
    { "Size X", "Tamaño X", "Tamanho X" },
    { "Size Y", "Tamaño Y", "Tamanho Y" },
    { "Size Z", "Tamaño Z", "Tamanho Z" },
    { "Skinned", "Con skinning", "Com skinning" },
    { "Slide Vertices", "Deslizar vértices", "Deslizar vértices" },
    { "Smart Euler", "Euler Inteligente", "Euler Inteligente" },
    { "Smart UV Project", "Proyección UV Inteligente", "Projeção UV Inteligente" },
    { "Smart UV Project: select faces first", "Proyección UV Inteligente: selecciona caras primero", "Projeção UV Inteligente: selecione faces primeiro" },
    { "Smooth", "Suave", "Suave" },
    { "Smooth Shading", "Sombreado Suave", "Sombreamento Suave" },
    { "Smoother", "Más suave", "Mais suave" },
    { "Snap Base", "Base de Snap", "Base de Snap" },
    { "Snap Base:", "Base de Snap:", "Base de Snap:" },
    { "Snap Target", "Destino de Snap", "Destino de Snap" },
    { "Snap Target for Individual Elements", "Destino de Snap para elementos individuales", "Destino de Snap para elementos individuais" },
    { "Snap Target:", "Destino de Snap:", "Destino de Snap:" },
    { "Solid Preview", "Vista Sólido", "Prévia Sólido" },
    { "Sound", "Sonido", "Som" },
    { "Sounds", "Sonidos", "Sons" },
    { "Source", "Fuente", "Fonte" },
    { "Spawn box", "Caja de nacimiento", "Caixa de nascimento" },
    { "Specular", "Especular", "Especular" },
    { "Speed", "Velocidad", "Velocidade" },
    { "Sphere", "Esfera", "Esfera" },
    { "Sphere Map (software)", "Mapa Esférico (software)", "Mapa Esférico (software)" },
    { "Sphere Projection", "Proyección de Esfera", "Projeção de Esfera" },
    { "Spin", "Giro", "Giro" },
    { "Spin random", "Azar del giro", "Giro aleatório (±)" },
    { "Split in Columns", "Dividir en columnas", "Dividir em colunas" },
    { "Split in Rows", "Dividir en filas", "Dividir em linhas" },
    { "Spot Cutoff", "Ángulo Spot", "Ângulo Spot" },
    { "Spot Exponent", "Exponente Spot", "Expoente Spot" },
    { "Spread", "Dispersión", "Dispersão" },
    { "Start", "Inicio", "Início" },
    { "Start angle", "Ángulo inicial", "Ângulo inicial" },
    { "Start:%d", "Inicio:%d", "Início:%d" },
    { "Starts at frame", "Arranca en el frame", "Começa no frame" },
    { "State", "Estado", "Estado" },
    { "Statistics", "Estadísticas", "Estatísticas" },
    { "Steps Viewport", "Pasos Viewport", "Passos Viewport" },
    { "Stop", "Parar", "Parar" },
    { "Stop the game before changing the scene", "Detén el juego antes de cambiar de escena", "Pare o jogo antes de trocar de cena" },
    { "Stop the game first", "Primero detén el juego", "Primeiro pare o jogo" },
    { "Stored", "Guardado", "Armazenado" },
    { "Streaming preview", "Vista previa del streaming", "Pré-visualização do streaming" },
    { "Stretch (seconds of velocity)", "Estiramiento (segundos de velocidad)", "Estiramento (segundos de velocidade)" },
    { "Stretch U", "Estirar U", "Esticar U" },
    { "Stretch V", "Estirar V", "Esticar V" },
    { "Stretched", "Estirada", "Esticada" },
    { "Subdivision Surface", "Superficie de Subdivisión", "Superfície de Subdivisão" },
    { "Subtract", "Restar", "Subtrair" },
    { "Summary", "Resumen", "Resumo" },
    { "Switch to 0-100%", "Cambiar a 0-100%", "Mudar para 0-100%" },
    { "Switch to 0-255", "Cambiar a 0-255", "Mudar para 0-255" },
    { "Sync Selection", "Sincronizar Selección", "Sincronizar Seleção" },
    { "Tag", "Etiqueta", "Etiqueta" },
    { "Target", "Objetivo", "Alvo" },
    { "Text Color", "Color de texto", "Cor do texto" },
    { "Texture", "Textura", "Textura" },
    { "Texture %d", "Textura %d", "Textura %d" },
    { "Texture Paint", "Pintura de Textura", "Pintura de Textura" },
    { "Texture Paint: the active part has no texture", "Pintura de Textura: la parte activa no tiene textura", "Pintura de Textura: a parte ativa não tem textura" },
    { "Texture layers", "Capas de textura", "Camadas de textura" },
    { "Texture of", "Textura de", "Textura de" },
    { "Texture saved", "Textura guardada", "Textura salva" },
    { "Textures", "Texturas", "Texturas" },
    { "The 3D mesh couldn't be loaded", "No se pudo cargar la malla 3D", "Não foi possível carregar a malha 3D" },
    { "The Object tab shows the BASE transform (the one that gets saved). Constraints modify it when drawing, so the object can appear elsewhere.", "La pestaña Objeto muestra la transformación BASE (la que se guarda). Las restricciones la modifican al dibujar, así que el objeto puede verse en otro lugar.", "A aba Objeto mostra a transformação BASE (a que é salva). As restrições a modificam ao desenhar, então o objeto pode aparecer em outro lugar." },
    { "The armature has its own clips", "El armature tiene clips propios", "O armature tem clipes próprios" },
    { "The clip library could not be read", "No se pudo leer la biblioteca de clips", "Não foi possível ler a biblioteca de clipes" },
    { "The default material can not be edited. Create a new material.", "El material por defecto no se puede editar. Crea un material nuevo.", "O material padrão não pode ser editado. Crie um novo material." },
    { "The default material can't be edited", "El material por defecto no se edita", "O material padrão não pode ser editado" },
    { "The external file is missing", "Falta el archivo externo", "O arquivo externo está faltando" },
    { "The file \"", "El archivo \"", "O arquivo \"" },
    { "The file couldn't be written", "No se pudo escribir el archivo", "Não foi possível gravar o arquivo" },
    { "The folder isn't empty", "La carpeta no está vacía", "A pasta não está vazia" },
    { "The instance could not be unpacked", "No se pudo desempaquetar la instancia", "Não foi possível desempacotar a instância" },
    { "The instance has nothing to unpack", "La instancia no tiene nada que desempaquetar", "A instância não tem nada para desempacotar" },
    { "The library file can't be opened", "No se puede abrir el archivo de la librería", "Não é possível abrir o arquivo da biblioteca" },
    { "The library has no proyecto.json", "La librería no tiene proyecto.json", "A biblioteca não tem proyecto.json" },
    { "The library has no such element", "La librería no tiene ese elemento", "A biblioteca não tem esse elemento" },
    { "The library is read-only", "La librería es de solo lectura", "A biblioteca é somente leitura" },
    { "The library isn't linked", "La librería no está vinculada", "A biblioteca não está vinculada" },
    { "The library's proyecto.json can't be read", "No se puede leer el proyecto.json de la librería", "Não é possível ler o proyecto.json da biblioteca" },
    { "The objects of the 3D meshes will be deleted too (Ctrl+Z brings them back).", "Los objetos de las mallas 3D también se borran (Ctrl+Z los devuelve).", "Os objetos das malhas 3D também serão excluídos (Ctrl+Z os traz de volta)." },
    { "The selected folders are deleted too if they end up empty.", "Las carpetas elegidas también se borran si quedan vacías.", "As pastas selecionadas também são excluídas se ficarem vazias." },
    { "The sound couldn't be decoded", "No se pudo decodificar el sonido", "Não foi possível decodificar o som" },
    { "The sound couldn't be read", "No se pudo leer el sonido", "Não foi possível ler o som" },
    { "The texture couldn't be loaded", "No se pudo cargar la textura", "Não foi possível carregar a textura" },
    { "The undo history still uses it", "El historial de deshacer todavía lo usa", "O histórico de desfazer ainda o usa" },
    { "There are no orphans", "No hay huérfanos", "Não há órfãos" },
    { "There is no active camera", "No hay cámara activa", "Não há câmera ativa" },
    { "There is no script editor (IDE) in the layout", "No hay un editor de scripts (IDE) en el layout", "Não há um editor de scripts (IDE) no layout" },
    { "There is no such prefab", "No existe ese prefab", "Esse prefab não existe" },
    { "This animation has no normals layer", "Esta animación no tiene capa de normales", "Esta animação não tem camada de normais" },
    { "This hierarchy clip only animates its root and its children", "Este clip de jerarquía solo anima a su raíz y a sus hijos", "Este clipe de hierarquia só anima sua raiz e seus filhos" },
    { "This is a scene: convert it to a game to simulate it", "Es una escena: conviértela en juego para simularla", "É uma cena: converta-a em jogo para simulá-la" },
    { "This resource can't be dropped in the 3D view", "Este recurso no se puede soltar en la vista 3D", "Este recurso não pode ser solto na vista 3D" },
    { "This resource can't be renamed", "Este recurso no se puede renombrar", "Este recurso não pode ser renomeado" },
    { "This resource type can't be deleted", "Este tipo de recurso no se puede borrar", "Este tipo de recurso não pode ser excluído" },
    { "This resource type can't be duplicated", "Este tipo de recurso no se puede duplicar", "Este tipo de recurso não pode ser duplicado" },
    { "Threshold", "Umbral", "Limiar" },
    { "Timeline", "Línea de Tiempo", "Linha do Tempo" },
    { "Times", "Tiempos", "Tempos" },
    { "Top", "Superior", "Superior" },
    { "Tracks", "Pistas", "Pistas" },
    { "Trail points", "Puntos de estela", "Pontos do rastro" },
    { "Trail step", "Paso de estela", "Passo do rastro" },
    { "Transform", "Transformar", "Transformar" },
    { "Transform Orientations", "Orientaciones de Transformación", "Orientações de Transformação" },
    { "Transform Pivot Point", "Punto de pivote", "Ponto pivô" },
    { "Translate", "Trasladar", "Transladar" },
    { "Translation", "Traslación", "Translação" },
    { "Transparent", "Transparente", "Transparente" },
    { "Triangles", "Triángulos", "Triângulos" },
    { "Triangulate Faces", "Triangular Caras", "Triangular Faces" },
    { "Turbulence", "Turbulencia", "Turbulência" },
    { "Type", "Tipo", "Tipo" },
    { "UV Editor", "Editor UV", "Editor UV" },
    { "UV Grid", "Grilla UV", "Grade UV" },
    { "UV Groups", "Grupos UV", "Grupos UV" },
    { "UV Maps", "Mapas UV", "Mapas UV" },
    { "UV Sphere", "Esfera UV", "Esfera UV" },
    { "UV: projected from view", "UV: proyectadas desde vista", "UV: projetadas da vista" },
    { "UV: projected from view (bounds)", "UV: proyectadas desde vista (límites)", "UV: projetadas da vista (limites)" },
    { "UVSphere", "EsferaUV", "EsferaUV" },
    { "Uniform", "Uniforme", "Uniforme" },
    { "Union", "Unión", "União" },
    { "Unlink", "Desvincular", "Desvincular" },
    { "Unloaded", "Descargada", "Descarregada" },
    { "Unpack", "Desempaquetar", "Desempacotar" },
    { "Unpack Prefab", "Desempaquetar prefab", "Desempacotar prefab" },
    { "Unwrap", "Desplegar", "Desdobrar" },
    { "Unwrap Angle Based", "Desplegar Basado en Ángulos", "Desdobrar Baseado em Ângulos" },
    { "Unwrap Conformal", "Desplegar Conforme", "Desdobrar Conforme" },
    { "Unwrap Minimum Stretch", "Desplegar Mínimo Estiramiento", "Desdobrar Mínimo Estiramento" },
    { "Unwrap: closed surface, mark seams first", "Desplegar: superficie cerrada, marca costuras primero", "Desdobrar: superfície fechada, marque costuras primeiro" },
    { "Unwrap: select faces first", "Desplegar: selecciona caras primero", "Desdobrar: selecione faces primeiro" },
    { "Upright (does not tilt)", "Vertical (no se inclina)", "Vertical (não se inclina)" },
    { "Use this file", "Usar este archivo", "Usar este ficheiro" },
    { "Users", "Usuarios", "Usuários" },
    { "Users selected", "Usuarios seleccionados", "Usuários selecionados" },
    { "Value", "Valor", "Valor" },
    { "Value Y", "Valor Y", "Valor Y" },
    { "Variation", "Variación", "Variação" },
    { "Vector", "Vector", "Vetor" },
    { "Velocity", "Velocidad", "Velocidade" },
    { "Vertex", "Vértice", "Vértice" },
    { "Vertex Animation", "Animación de Vértices", "Animação de Vértices" },
    { "Vertex Color", "Color de Vértice", "Cor de Vértice" },
    { "Vertex Groups", "Grupos de Vértices", "Grupos de Vértices" },
    { "Vertex Normal", "Normal de Vértice", "Normal de Vértice" },
    { "Vertex Paint", "Pintura de Vértices", "Pintura de Vértices" },
    { "Vertex groups", "Grupos de vértices", "Grupos de vértices" },
    { "Vertex groups optimized (1 bone/vertex)", "Grupos de vértices optimizados (1 hueso/vértice)", "Grupos de vértices otimizados (1 osso/vértice)" },
    { "Vertices", "Vértices", "Vértices" },
    { "Vertices connected", "Vértices conectados", "Vértices conectados" },
    { "Video", "Video", "Vídeo" },
    { "Videos", "Videos", "Vídeos" },
    { "View", "Vista", "Vista" },
    { "Viewpoint", "Punto de Vista", "Ponto de Vista" },
    { "Visible", "Visible", "Visível" },
    { "Warning", "Aviso", "Aviso" },
    { "Weight", "Peso", "Peso" },
    { "Weight Paint", "Pintura de Pesos", "Pintura de Pesos" },
    { "Width", "Ancho", "Largura" },
    { "Wireframe Preview", "Vista Alámbrica", "Prévia Aramado" },
    { "Wireframe: Only Visible", "Alambre: Solo lo Visible", "Aramado: Só o Visível" },
    { "With influence between 0 and 100 the billboard can flip 180 degrees when it crosses the camera. Use 100% to avoid it.", "Con influencia entre 0 y 100 el billboard puede girar 180 grados al cruzar la cámara. Con 100% no pasa.", "Com influência entre 0 e 100 o billboard pode girar 180 graus ao cruzar a câmera. Com 100% não acontece." },
    { "X Axis", "Eje X", "Eixo X" },
    { "X Euler Rotation", "X Rotación Euler", "X Rotação Euler" },
    { "X Location", "X Posición", "X Posição" },
    { "X Scale", "X Escala", "X Escala" },
    { "X-Ray", "Rayos X", "Raio-X" },
    { "XYZ Euler", "Euler XYZ", "Euler XYZ" },
    { "Y Axis", "Eje Y", "Eixo Y" },
    { "Y Euler Rotation", "Y Rotación Euler", "Y Rotação Euler" },
    { "Y Location", "Y Posición", "Y Posição" },
    { "Y Scale", "Y Escala", "Y Escala" },
    { "Yes", "Sí", "Sim" },
    { "Z Euler Rotation", "Z Rotación Euler", "Z Rotação Euler" },
    { "Z Location", "Z Posición", "Z Posição" },
    { "Z Scale", "Z Escala", "Z Escala" },
    { "ZBuffer Preview", "Vista ZBuffer", "Prévia ZBuffer" },
    { "[X: time]", "[X: tiempo]", "[X: tempo]" },
    { "[Y: value]", "[Y: valor]", "[Y: valor]" },
    { "all opaque", "todo opaco", "todo opaco" },
    { "along", "en", "em" },
    { "binary", "binario", "binário" },
    { "bone", "hueso", "osso" },
    { "bones", "huesos", "ossos" },
    { "center", "centro", "centro" },
    { "clip", "clip", "clipe" },
    { "clips", "clips", "clipes" },
    { "cube", "cubo", "cubo" },
    { "current frame", "frame actual", "frame atual" },
    { "cylinder", "cilindro", "cilindro" },
    { "deg", "grados", "graus" },
    { "deleted or renamed", "borrado o renombrado", "excluído ou renomeado" },
    { "done", "listo", "pronto" },
    { "edge", "arista", "aresta" },
    { "edge of a face", "arista de una cara", "aresta de uma face" },
    { "face", "cara", "face" },
    { "game", "juego", "jogo" },
    { "hierarchy", "jerarquía", "hierarquia" },
    { "hierarchy clip", "clip de jerarquía", "clipe de hierarquia" },
    { "hierarchy clips", "clips de jerarquía", "clipes de hierarquia" },
    { "islands", "islas", "ilhas" },
    { "missing", "falta", "faltando" },
    { "mono (1)", "mono (1)", "mono (1)" },
    { "new", "nuevo", "novo" },
    { "not loaded", "sin cargar", "não carregado" },
    { "not saved", "sin guardar", "não salvo" },
    { "not uploaded", "sin subir", "não enviado" },
    { "object", "objeto", "objeto" },
    { "objects", "objetos", "objetos" },
    { "open", "abierta", "aberta" },
    { "part", "parte", "parte" },
    { "parts", "partes", "partes" },
    { "prefab", "prefab", "prefab" },
    { "preview", "vista previa", "prévia" },
    { "projection", "proyección", "projeção" },
    { "read-only", "solo lectura", "somente leitura" },
    { "read-only library", "librería de solo lectura", "biblioteca somente leitura" },
    { "root", "raíz", "raiz" },
    { "scene", "escena", "cena" },
    { "select a mesh object first", "elegí primero un objeto malla", "escolha primeiro um objeto malha" },
    { "soon", "pronto", "em breve" },
    { "sphere", "esfera", "esfera" },
    { "start", "inicial", "inicial" },
    { "stereo (2)", "estéreo (2)", "estéreo (2)" },
    { "track", "pista", "trilha" },
    { "tracks", "pistas", "trilhas" },
    { "triangle", "triángulo", "triângulo" },
    { "triangles", "triángulos", "triângulos" },
    { "unsaved", "sin guardar", "não salvo" },
    { "vertex", "vértice", "vértice" },
    { "vertices", "vértices", "vértices" },
    { "view", "vista", "vista" },
    { "with mipmaps", "con mipmaps", "com mipmaps" },
    { "with transparency", "con transparencias", "com transparência" },
    { "without mipmaps", "sin mipmaps", "sem mipmaps" },
    { "you want to select (Esc to cancel)", "a seleccionar (Esc para cancelar)", "a selecionar (Esc para cancelar)" },
};

static const unsigned int W3D_LANG_ENTRADAS = sizeof(W3dLangTabla) / sizeof(W3dLangTabla[0]);

#endif
